// Code generated by ogen, DO NOT EDIT.

package openaiclient

// setDefaults set default value of fields.
func (s *CreateChatCompletionRequest) setDefaults() {
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := int(4096)
		s.MaxTokens.SetTo(val)
	}
	{
		val := float64(0)
		s.PresencePenalty.SetTo(val)
	}
	{
		val := float64(0)
		s.FrequencyPenalty.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateEditRequest) setDefaults() {
	{
		val := string("")
		s.Input.SetTo(val)
	}
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateFineTuneRequest) setDefaults() {
	{
		val := string("curie")
		s.Model.SetTo(val)
	}
	{
		val := int(4)
		s.NEpochs.SetTo(val)
	}
	{
		s.BatchSize.Null = true
	}
	{
		s.LearningRateMultiplier.Null = true
	}
	{
		val := float64(0.01)
		s.PromptLossWeight.SetTo(val)
	}
	{
		val := bool(false)
		s.ComputeClassificationMetrics.SetTo(val)
	}
	{
		s.ClassificationNClasses.Null = true
	}
	{
		s.ClassificationPositiveClass.Null = true
	}
	{
		s.Suffix.Null = true
	}
}

// setDefaults set default value of fields.
func (s *CreateImageEditRequest) setDefaults() {
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := CreateImageEditRequestSize("1024x1024")
		s.Size.SetTo(val)
	}
	{
		val := CreateImageEditRequestResponseFormat("url")
		s.ResponseFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateImageEditRequestForm) setDefaults() {
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := CreateImageEditRequestSize("1024x1024")
		s.Size.SetTo(val)
	}
	{
		val := CreateImageEditRequestResponseFormat("url")
		s.ResponseFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateImageRequest) setDefaults() {
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := CreateImageRequestSize("1024x1024")
		s.Size.SetTo(val)
	}
	{
		val := CreateImageRequestResponseFormat("url")
		s.ResponseFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateImageVariationRequest) setDefaults() {
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := CreateImageVariationRequestSize("1024x1024")
		s.Size.SetTo(val)
	}
	{
		val := CreateImageVariationRequestResponseFormat("url")
		s.ResponseFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateImageVariationRequestForm) setDefaults() {
	{
		val := int(1)
		s.N.SetTo(val)
	}
	{
		val := CreateImageVariationRequestSize("1024x1024")
		s.Size.SetTo(val)
	}
	{
		val := CreateImageVariationRequestResponseFormat("url")
		s.ResponseFormat.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateModerationRequest) setDefaults() {
	{
		val := string("text-moderation-latest")
		s.Model.SetTo(val)
	}
}
